server:
  port: 8083
spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ams-codelist-service
              uri: lb://AMS-CODELIST
              predicates:
                - Path=/codelist/**
              filters:
                - StripPrefix: 1
                - name: CircuitBreaker
                  args:
                    name: circuitBreakerCall
                    fallbackUri: forward:/fallback
            - id: ams-user-service
              uri: lb://AMS-USER
              predicates:
                - Path=/user/**
              filters:
                - StripPrefix: 1
                - name: CircuitBreaker
                  args:
                    name: circuitBreakerCall
                    fallbackUri: forward:/fallback
          discovery:
            locator:
              lower-case-service-id: true
              enabled: true
    globalcors:
      corsConfigurations:
        '[/**]':
          allowedOrigins: "http://localhost:3000"
          allowedMethods:
            - GET
            - POST
            - DELETE
            - PUT
          allowedHeaders: "*"
resilience4j.circuitbreaker:
  instances:
    circuitBreakerCall:
      registerHealthIndicator: true
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 10s
      permittedNumberOfCallsInHalfOpenState: 3
      minimumNumberOfCalls: 5